const barajaEspanola = [
    { id: 1, nombre: "As de Oros", palo: "oros",  },
    { id: 2, nombre: "Dos de Oros", palo: "oros", ruta: "imagenes/oros/2.jpg" },
    { id: 3, nombre: "Tres de Oros", palo: "oros", ruta: "imagenes/oros/3.jpg" },
    { id: 4, nombre: "Cuatro de Oros", palo: "oros", ruta: "imagenes/oros/4.jpg" },
    { id: 5, nombre: "Cinco de Oros", palo: "oros", ruta: "imagenes/oros/5.jpg" },
    { id: 6, nombre: "Seis de Oros", palo: "oros", ruta: "imagenes/oros/6.jpg" },
    { id: 7, nombre: "Siete de Oros", palo: "oros", ruta: "imagenes/oros/7.jpg" },
    { id: 10, nombre: "Sota de Oros", palo: "oros", ruta: "imagenes/oros/10.jpg" },
    { id: 11, nombre: "Caballo de Oros", palo: "oros", ruta: "imagenes/oros/11.jpg" },
    { id: 12, nombre: "Rey de Oros", palo: "oros", ruta: "imagenes/oros/12.jpg" },
  
    { id: 13, nombre: "As de Copas", palo: "copas", ruta: "imagenes/copas/1.jpg" },
    { id: 14, nombre: "Dos de Copas", palo: "copas", ruta: "imagenes/copas/2.jpg" },
    { id: 15, nombre: "Tres de Copas", palo: "copas", ruta: "imagenes/copas/3.jpg" },
    { id: 16, nombre: "Cuatro de Copas", palo: "copas", ruta: "imagenes/copas/4.jpg" },
    { id: 17, nombre: "Cinco de Copas", palo: "copas", ruta: "imagenes/copas/5.jpg" },
    { id: 18, nombre: "Seis de Copas", palo: "copas", ruta: "imagenes/copas/6.jpg" },
    { id: 19, nombre: "Siete de Copas", palo: "copas", ruta: "imagenes/copas/7.jpg" },
    { id: 20, nombre: "Sota de Copas", palo: "copas", ruta: "imagenes/copas/10.jpg" },
    { id: 21, nombre: "Caballo de Copas", palo: "copas", ruta: "imagenes/copas/11.jpg" },
    { id: 22, nombre: "Rey de Copas", palo: "copas", ruta: "imagenes/copas/12.jpg" },
  
    { id: 23, nombre: "As de Espadas", palo: "espadas", ruta: "imagenes/espadas/1.jpg" },
    { id: 24, nombre: "Dos de Espadas", palo: "espadas", ruta: "imagenes/espadas/2.jpg" },
    { id: 25, nombre: "Tres de Espadas", palo: "espadas", ruta: "imagenes/espadas/3.jpg" },
    { id: 26, nombre: "Cuatro de Espadas", palo: "espadas", ruta: "imagenes/espadas/4.jpg" },
    { id: 27, nombre: "Cinco de Espadas", palo: "espadas", ruta: "imagenes/espadas/5.jpg" },
    { id: 28, nombre: "Seis de Espadas", palo: "espadas", ruta: "imagenes/espadas/6.jpg" },
    { id: 29, nombre: "Siete de Espadas", palo: "espadas", ruta: "imagenes/espadas/7.jpg" },
    { id: 30, nombre: "Sota de Espadas", palo: "espadas", ruta: "imagenes/espadas/10.jpg" },
    { id: 31, nombre: "Caballo de Espadas", palo: "espadas", ruta: "imagenes/espadas/11.jpg" },
    { id: 32, nombre: "Rey de Espadas", palo: "espadas", ruta: "imagenes/espadas/12.jpg" },
  
    { id: 33, nombre: "As de Bastos", palo: "bastos", ruta: "imagenes/bastos/1.jpg" },
    { id: 34, nombre: "Dos de Bastos", palo: "bastos", ruta: "imagenes/bastos/2.jpg" },
    { id: 35, nombre: "Tres de Bastos", palo: "bastos", ruta: "imagenes/bastos/3.jpg" },
    { id: 36, nombre: "Cuatro de Bastos", palo: "bastos", ruta: "imagenes/bastos/4.jpg" },
    { id: 37, nombre: "Cinco de Bastos", palo: "bastos", ruta: "imagenes/bastos/5.jpg" },
    { id: 38, nombre: "Seis de Bastos", palo: "bastos", ruta: "imagenes/bastos/6.jpg" },
    { id: 39, nombre: "Siete de Bastos", palo: "bastos", ruta: "imagenes/bastos/7.jpg" },
    { id: 40, nombre: "Sota de Bastos", palo: "bastos", ruta: "imagenes/bastos/10.jpg" },
    { id: 41, nombre: "Caballo de Bastos", palo: "bastos", ruta: "imagenes/bastos/11.jpg" },
    { id: 42, nombre: "Rey de Bastos", palo: "bastos", ruta: "imagenes/bastos/12.jpg" }
  ];